version: "3.3"

services:
    shiny:
      build:
        context: .
        dockerfile: Dockerfile
      
      image: ispi_compose
      
      restart: always

      user: shiny

      ports:
        - '3003:3838'